CREATE TABLE [adi].[CignaMA_MedAdherencePlans] (
    [CignaMAMedAdherencePlansKey] INT           IDENTITY (1, 1) NOT NULL,
    [SrcFileName]                 VARCHAR (100) NULL,
    [FileDate]                    DATE          NULL,
    [CreateDate]                  DATETIME      DEFAULT (sysdatetime()) NULL,
    [CreateBy]                    VARCHAR (100) DEFAULT (suser_sname()) NULL,
    [OriginalFileName]            VARCHAR (100) NULL,
    [LastUpdatedBy]               VARCHAR (100) NULL,
    [LastUpdatedDate]             DATETIME      NULL,
    [DataDate]                    DATE          NULL,
    [ContractID]                  VARCHAR (10)  NULL,
    [PBP]                         VARCHAR (10)  NULL,
    [Region]                      VARCHAR (20)  NULL,
    [Market]                      VARCHAR (20)  NULL,
    [CurrentYRFills]              VARCHAR (10)  NULL,
    [PCPNPI]                      VARCHAR (50)  NULL,
    [PCPLastName]                 VARCHAR (50)  NULL,
    [PCPFirstName]                VARCHAR (50)  NULL,
    [PCP]                         VARCHAR (50)  NULL,
    [QNXTPCPID]                   VARCHAR (50)  NULL,
    [PODName]                     VARCHAR (50)  NULL,
    [MemberID]                    VARCHAR (20)  NULL,
    [LastName]                    VARCHAR (50)  NULL,
    [FirstName]                   VARCHAR (50)  NULL,
    [TermDate]                    DATE          NULL,
    [DenominatorDaysYTD]          VARCHAR (5)   NULL,
    [DaysCoveredYTD]              VARCHAR (5)   NULL,
    [CURRENTYEARPDC_YTD]          VARCHAR (10)  NULL,
    [PDCR12]                      VARCHAR (10)  NULL,
    [One_YR_prior_PDC]            VARCHAR (10)  NULL,
    [Two_YR_prior_PDC]            VARCHAR (10)  NULL,
    [Three_YR_prior_PDC]          VARCHAR (10)  NULL,
    [NonAdherentDaysRemaining]    VARCHAR (5)   NULL,
    [PossibleToMeet]              VARCHAR (10)  NULL,
    [DrugClass]                   VARCHAR (50)  NULL,
    [MedicationName]              VARCHAR (50)  NULL,
    [DaysSupply]                  VARCHAR (5)   NULL,
    [MedicationTier]              VARCHAR (10)  NULL,
    [FirstFillDate]               DATE          NULL,
    [LastFillDate]                DATE          NULL,
    [NextFillDueDate]             DATE          NULL,
    [PharmacyType]                VARCHAR (10)  NULL,
    [PharmacyTypeDesc]            VARCHAR (50)  NULL,
    [PatResdDescr]                VARCHAR (50)  NULL,
    [RowStatus]                   CHAR (1)      DEFAULT ((0)) NULL,
    CONSTRAINT [PK_CignaMA_MedAdherencePlans] PRIMARY KEY CLUSTERED ([CignaMAMedAdherencePlansKey] ASC)
);

