CREATE TABLE [adi].[CignaMACareOpps] (
    [careopsCignaMaKey]  INT           IDENTITY (1, 1) NOT NULL,
    [SrcFileName]        VARCHAR (100) NOT NULL,
    [LoadDate]           DATE          NOT NULL,
    [DataDate]           DATE          NOT NULL,
    [CreatedDate]        DATETIME      CONSTRAINT [DF_adiCignaMACareOpps_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]          VARCHAR (50)  CONSTRAINT [DF_adiCignaMACareOpps_CreatedBy] DEFAULT (suser_sname()) NOT NULL,
    [LastUpdatedDate]    DATETIME      CONSTRAINT [DF_adiCignaMACareOpps_LastUpdatedDate] DEFAULT (getdate()) NOT NULL,
    [LastUpdatedBy]      VARCHAR (50)  CONSTRAINT [DF_adiCignaMACareOpps_LastUpdatedBy] DEFAULT (suser_sname()) NOT NULL,
    [DOS_Yr]             VARCHAR (10)  NULL,
    [Op_Mkt]             VARCHAR (10)  NULL,
    [H_Plan]             VARCHAR (10)  NULL,
    [Mkt_Specific]       VARCHAR (10)  NULL,
    [P4Q]                VARCHAR (10)  NULL,
    [Living_Well]        VARCHAR (50)  NULL,
    [Mbr_Dcsd]           VARCHAR (50)  NULL,
    [Term_Date]          DATE          NULL,
    [POD]                VARCHAR (50)  NULL,
    [PCP_Name]           VARCHAR (50)  NULL,
    [Mbr_ID]             VARCHAR (50)  NULL,
    [Mbr_Name]           VARCHAR (50)  NULL,
    [Mbr_Dob]            DATE          NULL,
    [OPP_SCORE]          VARCHAR (50)  NULL,
    [BMI]                VARCHAR (50)  NULL,
    [BCS]                VARCHAR (50)  NULL,
    [COAFS]              VARCHAR (50)  NULL,
    [COAMR]              VARCHAR (50)  NULL,
    [COAPA]              VARCHAR (50)  NULL,
    [COLO]               VARCHAR (50)  NULL,
    [DRE]                VARCHAR (50)  NULL,
    [A1c]                VARCHAR (50)  NULL,
    [NEPH]               VARCHAR (50)  NULL,
    [CBP]                VARCHAR (50)  NULL,
    [MRP]                VARCHAR (50)  NULL,
    [PCR]                VARCHAR (50)  NULL,
    [OSTEO]              VARCHAR (50)  NULL,
    [DMARD]              VARCHAR (50)  NULL,
    [ODB]                VARCHAR (50)  NULL,
    [ACEARB]             VARCHAR (50)  NULL,
    [STAT]               VARCHAR (50)  NULL,
    [SUPD]               VARCHAR (50)  NULL,
    [SPC]                VARCHAR (50)  NULL,
    [Mbr_Phn]            VARCHAR (50)  NULL,
    [PCP_ID]             VARCHAR (50)  NULL,
    [PCP_NPI]            VARCHAR (50)  NULL,
    [PCP_Phn]            VARCHAR (50)  NULL,
    [Last_Screening_DOS] DATE          NULL,
    [Provider_Name]      VARCHAR (50)  NULL,
    [RISK_SCORE]         VARCHAR (50)  NULL,
    [AttrPCPID]          VARCHAR (50)  NULL,
    [AttrPCPName]        VARCHAR (50)  NULL,
    [AttrPOD]            VARCHAR (50)  NULL,
    [CM_Flag]            VARCHAR (50)  NULL,
    [RiskScoreGroup]     VARCHAR (50)  NULL,
    [OPPScoreGroup]      VARCHAR (50)  NULL,
    [CopLoadStatus]      TINYINT       DEFAULT ((0)) NULL
);

