CREATE TABLE [adi].[NtfCignaMATXWklyCensus] (
    [NtfCignaMATXWklyCensusKey] INT           IDENTITY (1, 1) NOT NULL,
    [SrcFileName]               VARCHAR (100) NOT NULL,
    [LoadDate]                  DATE          NOT NULL,
    [DataDate]                  DATE          NOT NULL,
    [CreatedDate]               DATETIME      CONSTRAINT [DF_adiNtfCignaMATXWklyCensus_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]                 VARCHAR (50)  CONSTRAINT [DF_adiNtfCignaMATXWklyCensus_CreatedBy] DEFAULT (suser_sname()) NOT NULL,
    [LastUpdatedDate]           DATETIME      CONSTRAINT [DF_adiNtfCignaMATXWklyCensus_LastUpdatedDate] DEFAULT (getdate()) NOT NULL,
    [LastUpdatedBy]             VARCHAR (50)  CONSTRAINT [DF_adiNtfCignaMATXWklyCensus_LastUpdatedBy] DEFAULT (suser_sname()) NOT NULL,
    [member_id]                 VARCHAR (50)  NULL,
    [Member_Name]               VARCHAR (50)  NULL,
    [admission_date]            VARCHAR (20)  NULL,
    [authorization_number]      VARCHAR (50)  NULL,
    [facility_name]             VARCHAR (50)  NULL,
    [facility_id]               VARCHAR (50)  NULL,
    [diagnosis_desc]            VARCHAR (500) NULL,
    [prov_first]                VARCHAR (50)  NULL,
    [prov_last]                 VARCHAR (50)  NULL,
    [admission_type_desc]       VARCHAR (500) NULL,
    [actual_discharge_date]     VARCHAR (20)  NULL,
    [ccmspod]                   VARCHAR (50)  NULL,
    [authorized_admission_date] VARCHAR (20)  NULL,
    [event_mgmt_status_desc]    VARCHAR (50)  NULL,
    [actual_los]                VARCHAR (10)  NULL,
    [diagnosis_code]            VARCHAR (50)  NULL,
    [diag_1st_3]                VARCHAR (50)  NULL,
    [provider_first_name]       VARCHAR (50)  NULL,
    [managing_provider]         VARCHAR (50)  NULL,
    [provider_last_name]        VARCHAR (50)  NULL,
    [admission_reason]          VARCHAR (50)  NULL,
    [benefit_plan]              VARCHAR (50)  NULL,
    [attending_provider]        VARCHAR (50)  NULL,
    [ezcapid]                   VARCHAR (50)  NULL,
    [los]                       VARCHAR (50)  NULL,
    [pcp_name]                  VARCHAR (50)  NULL,
    [ezpcpfirst]                VARCHAR (50)  NULL,
    [ezpcplast]                 VARCHAR (50)  NULL,
    [ezpcpid]                   VARCHAR (50)  NULL,
    [obscnt]                    VARCHAR (50)  NULL,
    [ltaccnt]                   VARCHAR (50)  NULL,
    [ezpod]                     VARCHAR (50)  NULL,
    [mkt]                       VARCHAR (50)  NULL,
    [disease_state]             VARCHAR (50)  NULL,
    [opt]                       VARCHAR (50)  NULL,
    [program]                   VARCHAR (50)  NULL,
    [group]                     VARCHAR (50)  NULL,
    [bed_type]                  VARCHAR (50)  NULL,
    [data_date]                 DATETIME      NULL,
    [source]                    VARCHAR (50)  NULL,
    [link_date]                 VARCHAR (20)  NULL,
    [linkdate_dt]               DATE          NULL,
    [ezpod_abbr]                VARCHAR (50)  NULL,
    [event_status]              VARCHAR (50)  NULL,
    [birth]                     VARCHAR (20)  NULL,
    [Age_at_Admit]              VARCHAR (10)  NULL,
    [Market_member_months]      VARCHAR (10)  NULL,
    [request_date]              VARCHAR (20)  NULL,
    [readmit1_auth]             VARCHAR (50)  NULL,
    [readmit1_diag]             VARCHAR (50)  NULL,
    [readmit1_diagdesc]         VARCHAR (500) NULL,
    [readmit2_auth]             VARCHAR (50)  NULL,
    [readmit2_diag]             VARCHAR (50)  NULL,
    [readmit2_diagdesc]         VARCHAR (500) NULL,
    [readmit3_auth]             VARCHAR (50)  NULL,
    [readmit3_diag]             VARCHAR (50)  NULL,
    [readmit3_diagdesc]         VARCHAR (500) NULL,
    [pended]                    VARCHAR (50)  NULL,
    [dx_category]               VARCHAR (50)  NULL,
    [MDC_Code]                  VARCHAR (10)  NULL,
    [InstPaid]                  VARCHAR (10)  NULL,
    [ProfPaid]                  VARCHAR (10)  NULL,
    [discharge_status]          VARCHAR (10)  NULL,
    [FacilityParFlag]           VARCHAR (10)  NULL,
    [Admission_Procedure1]      VARCHAR (50)  NULL,
    [Admission_Procedure2]      VARCHAR (50)  NULL,
    [Admission_Procedure3]      VARCHAR (50)  NULL,
    [Admission_Procedure4]      VARCHAR (50)  NULL,
    [AdmitNotificationDays]     SMALLINT      NULL,
    [RegionCode]                VARCHAR (50)  NULL,
    [Hcode]                     VARCHAR (50)  NULL,
    [PBP]                       VARCHAR (50)  NULL,
    [RowStatus]                 TINYINT       DEFAULT ((0)) NULL,
    PRIMARY KEY CLUSTERED ([NtfCignaMATXWklyCensusKey] ASC)
);

