


CREATE VIEW [dbo].[tmp_VW_AH_MEMBERSHIP]
AS
SELECT DISTINCT 
	REPLACE(memberid,'*','') AS Member_ID, 
       '' AS MEDICAID_ID, 
       a.firstname AS MEMBER_FIRST_NAME, 
       middlename AS MEMBER_MI, 
       a.lastname AS MEMBER_LAST_NAME, 
      CONVERT(DATE, DOB) AS DATE_OF_BIRTH, 
       gender AS MEMBER_GENDER, 
       Addressline1 AS HOME_ADDRESS, 
       city AS HOME_CITY, 
       [state] AS HOME_STATE, 
       LEFT(zip,5) AS HOME_ZIPCODE, 
       '' MAILING_ADDRESS, 
       '' MAILING_CITY, 
       '' MAILING_STATE, 
       '' MAILING_ZIP, 
       homephone AS HOME_PHONE, 
       '' ADDITIONAL_PHONE, 
       '' CELL_PHONE, 
       LanguageDesc AS [Language], 
       '' Ethnicity, 
       a.medicareid as MEDICARE_ID, 
       '' MEMBER_ORG_EFF_DATE, 
       '' MEMBER_CONT_EFF_DATE, 
       '' MEMBER_CUR_EFF_DATE, 
       '' MEMBER_CUR_TERM_DATE, 
       '' RESP_FIRST_NAME, 
       '' RESP_LAST_NAME, 
       '' RESP_RELATIONSHIP, 
       '' RESP_ADDRESS, 
       '' RESP_ADDRESS2, 
       '' RESP_CITY, 
       '' RESP_STATE, 
       '' RESP_ZIP, 
       '' RESP_PHONE, 
       risk_score AS PRIMARY_RISK_FACTOR, 
       '' COUNT_OPEN_CARE_OPPS, 
       '' INP_ADMITS_LAST_12_MOS, 
       '' LAST_INP_DISCHARGE, 
       '' POST_DISCHARGE_FUP_VISIT, 
       '' INP_FUP_WITHIN_7_DAYS, 
       '' ER_VISITS_LAST_12_MOS, 
       '' LAST_ER_VISIT, 
       '' POST_ER_FUP_VISIT, 
       '' ER_FUP_WITHIN_7_DAYS, 
       CONVERT(DATE,lastpcpvisit) AS LAST_PCP_VISIT, 
       '' LAST_PCP_PRACTICE_SEEN, 
       '' LAST_BH_VISIT, 
       '' LAST_BH_PRACTICE_SEEN, 
       '' TOTAL_COSTS_LAST_12_MOS, 
       '' INP_COSTS_LAST_12_MOS, 
       '' ER_COSTS_LAST_12_MOS,
		'' OUTP_COSTS_LAST_12_MOS,
		'' PHARMACY_COSTS_LAST_12_MOS,
		'' PRIMARY_CARE_COSTS_LAST_12_MOS,
		'' BEHAVIORAL_COSTS_LAST_12_MOS,
		'' OTHER_OFFICE_COSTS_LAST_12_MOS,
		'' NEXT_PREVENTATIVE_VISIT_DUE,
		'' Email,
		'' Race,
		'Cigna_MA' Client_ID,
		'' ACE_MEmber_ID,
		'' Carrier_Member_ID

FROM [ACDW_CLMS_CIGNA_MA].[adi].[tmp_CignaMAMembership] a
join ACECAREDW.adw.fctProviderRoster b on b.NPI = a.npid and b.ClientKey = 12 and IsActive = 1 and getdate() between B.EffectiveDate and B.ExpirationDate
WHERE a.DATADATE = (SELECT MAX(DATADATE) FROM [ACDW_CLMS_CIGNA_MA].[adi].[tmp_CignaMAMembership])

 
